svg were added + some changes in code (play img, uppercase..)
MateAcademy-FE-study/decolette_SAL pull request #8
Opened 2018-04-02 08:52 UTC by petrychenkodev

2018-04-02 17:35 UTC, tatsiak reviewed
dude уже png, но фон все равно белый
кнопка "УСЛУГИ И ЦЕНЫ" и выбор языка отличаются от того что есть в макете

2018-04-02 17:36 UTC, tatsiak commented
кнопка "УСЛУГИ И ЦЕНЫ" и выбор языка отличаются от макета

2018-04-02 17:39 UTC, tatsiak requested changes
надо доделать места о которых говорил Юра (кнопка "УСЛУГИ И ЦЕНЫ", фон за чуваком, выбор языка итд)

2018-04-03 07:16 UTC, petrychenkodev commented
visual changes in header

2018-04-05 05:57 UTC, merged